#!/usr/bin/env php
<?php

error_reporting(E_ALL);
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');

require_once ($root = (getcwd() ?: __DIR__)).'/vendor/autoload.php';

Dof\Framework\Cli\Kernel::handle($root, $argv);
